"""PDF Report generation engine for AI Resume Analyzer.

Implements PRD F9 using fpdf2 to build a downloadable summary report.
Reflects single source of truth scoring, horizontal score bars with visible tracks,
weighted contribution formulas, and Indian-market ATS recommendations.
"""

from datetime import datetime
from typing import Any, Dict, List
from fpdf import FPDF


class PDFReport(FPDF):
    """Custom stylized PDF report for ResumeCheck."""

    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Brand header bar
        self.set_fill_color(31, 111, 92)  # #1F6F5C Green
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(255, 255, 255)
        self.set_xy(15, 4)
        self.cell(0, 10, "ResumeCheck  |  AI Resume Analysis & ATS Report", 0, 0, "L")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(226, 232, 240)
        self.set_xy(130, 4)
        self.cell(65, 10, datetime.now().strftime("%d/%m/%Y"), 0, 0, "R")
        self.ln(18)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 8, f"Page {self.page_no()} of {{nb}}  --  Generated by ResumeCheck (Built by Priyanshu Gupta)", 0, 0, "C")


def _sanitize(text: Any) -> str:
    """Sanitize strings for standard core PDF fonts (latin-1 compatible)."""
    if text is None:
        return ""
    s = str(text)
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2014": "--",
        "\u2013": "-",
        "\u2022": "*",
        "\u25cf": "*",
        "\u25aa": "*",
        "\u2026": "...",
        "\u00a0": " ",
        "•": "*",
        "✓": "[OK]",
        "✔": "[OK]",
        "₹": "Rs. ",
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    return s.encode("latin-1", "replace").decode("latin-1")


def _extract_skill_names(items: List[Any]) -> List[str]:
    """Helper to extract names whether items are strings or dictionaries."""
    names = []
    for item in items:
        if isinstance(item, dict):
            names.append(item.get("name", str(item)))
        else:
            names.append(str(item))
    return names


def generate_pdf_report(analysis_data: Dict[str, Any]) -> bytes:
    """Generate a formatted PDF report with single source of truth scoring."""
    pdf = PDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    filename = analysis_data.get("filename", "Uploaded Resume")
    score_data = analysis_data.get("scores", {})
    overall_score = score_data.get("overall_score", 0)
    label = score_data.get("label", "N/A")
    summary_text = score_data.get("summary", "")
    sub_scores = score_data.get("sub_scores", {})
    weighted_points = score_data.get("weighted_points", {})
    formula_text = score_data.get("formula_text", "")
    skills = analysis_data.get("skills", {})
    ats_results = analysis_data.get("ats", {})
    ai_feedback = analysis_data.get("ai_feedback")

    # Title & Metadata
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 8, _sanitize(f"Resume Analysis Report: {filename}"), ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 116, 139)
    words = analysis_data.get("word_count", 0)
    target_job = analysis_data.get("target_job", {})
    role_info = f"  |  Role: {target_job.get('title')}" if target_job.get("title") else ""
    pdf.cell(0, 5, _sanitize(f"Word Count: {words} words{role_info}  |  Date: {datetime.now().strftime('%d/%m/%Y')}"), ln=True)
    pdf.ln(4)

    # Overall Score Box
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.rect(15, pdf.get_y(), 180, 22, "DF")

    pdf.set_xy(20, pdf.get_y() + 3)
    pdf.set_font("Helvetica", "B", 22)
    if overall_score >= 85:
        pdf.set_text_color(22, 101, 52)  # Green
    elif overall_score >= 70:
        pdf.set_text_color(31, 111, 92)  # Forest Green
    elif overall_score >= 40:
        pdf.set_text_color(180, 83, 9)   # Amber
    else:
        pdf.set_text_color(185, 28, 28)  # Red
    pdf.cell(32, 12, f"{overall_score}/100", 0, 0, "L")

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 12, _sanitize(f"Rating: {label}"), 0, 0, "L")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.set_xy(90, pdf.get_y() + 2)
    pdf.multi_cell(100, 4, _sanitize(summary_text))

    pdf.ln(12)

    # Component Scores Breakdown (Horizontal bars with visible grey track)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 7, "Score Breakdown & Weighted Contribution", ln=True)
    pdf.ln(1)

    components = [
        ("Skill match", 50, sub_scores.get("skill_match", 0), weighted_points.get("skill_match", round(0.50 * sub_scores.get("skill_match", 0), 1))),
        ("Text relevance", 25, sub_scores.get("text_similarity", 0), weighted_points.get("text_similarity", round(0.25 * sub_scores.get("text_similarity", 0), 1))),
        ("Structure", 15, sub_scores.get("structure_completeness", 0), weighted_points.get("structure_completeness", round(0.15 * sub_scores.get("structure_completeness", 0), 1))),
        ("ATS quality", 10, sub_scores.get("ats_quality", 0), weighted_points.get("ats_quality", round(0.10 * sub_scores.get("ats_quality", 0), 1))),
    ]

    for name, weight, score_val, pts in components:
        curr_y = pdf.get_y()

        # Label & Weight
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(30, 41, 59)
        pdf.set_xy(15, curr_y)
        pdf.cell(50, 5, _sanitize(f"{name} (weight {weight}%):"), 0, 0, "L")

        # Score text
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(16, 5, f"{score_val}/100", 0, 0, "L")

        # Horizontal Bar: Grey track & colored fill
        bar_x = 84
        bar_y = curr_y + 1.5
        track_w = 60
        bar_h = 3.5

        # Draw grey track
        pdf.set_fill_color(226, 232, 240)  # #E2E8F0
        pdf.rect(bar_x, bar_y, track_w, bar_h, "F")

        # Draw filled progress
        fill_w = max(0.5, (float(score_val) / 100.0) * track_w) if score_val > 0 else 0
        if fill_w > 0:
            if score_val < 40:
                pdf.set_fill_color(220, 38, 38)  # Red for under 40
            else:
                pdf.set_fill_color(31, 111, 92)  # Primary Green
            pdf.rect(bar_x, bar_y, fill_w, bar_h, "F")

        # Points column
        pdf.set_xy(150, curr_y)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(31, 111, 92) if score_val >= 40 else pdf.set_text_color(185, 28, 28)
        pdf.cell(45, 5, _sanitize(f"{pts} of {weight}.0 pts"), 0, 1, "R")
        pdf.ln(1)

    # Formula text under the chart
    pdf.ln(2)
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    curr_y = pdf.get_y()
    pdf.rect(15, curr_y, 180, 8, "DF")
    pdf.set_xy(18, curr_y + 1.5)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 116, 139)
    formula_str = formula_text or f"Overall {overall_score} = 50% x {sub_scores.get('skill_match',0)} + 25% x {sub_scores.get('text_similarity',0)} + 15% x {sub_scores.get('structure_completeness',0)} + 10% x {sub_scores.get('ats_quality',0)}"
    pdf.cell(0, 5, _sanitize(f"Formula: {formula_str}"), 0, 1, "L")
    pdf.ln(6)

    # Section 1: Skills Breakdown
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 7, "1. Skill Match & Gap Analysis", ln=True)
    pdf.ln(1)

    matched_list = _extract_skill_names(skills.get("matched", []))
    missing_list = _extract_skill_names(skills.get("missing", []))
    extra_list = _extract_skill_names(skills.get("extra", []))

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(22, 101, 52)
    pdf.cell(0, 5, _sanitize(f"Matched Skills ({len(matched_list)}):"), ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(51, 65, 85)
    matched_text = ", ".join(matched_list) if matched_list else "None detected"
    pdf.multi_cell(0, 5, _sanitize(matched_text))
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(185, 28, 28)
    pdf.cell(0, 5, _sanitize(f"Missing Key Skills ({len(missing_list)}):"), ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(51, 65, 85)
    missing_text = ", ".join(missing_list) if missing_list else "None! Excellent coverage."
    pdf.multi_cell(0, 5, _sanitize(missing_text))
    pdf.ln(2)

    if extra_list:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(0, 5, _sanitize(f"Additional Candidate Skills ({len(extra_list)}):"), ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _sanitize(", ".join(extra_list[:25])))
        pdf.ln(2)

    # Section 2: ATS Compliance Checklist
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 7, "2. ATS Compliance & Formatting Checks", ln=True)
    pdf.ln(1)

    checks = ats_results.get("checks", [])
    for check in checks:
        status_symbol = "[PASS]" if check.get("status") == "pass" else "[WARN]"
        pdf.set_font("Helvetica", "B", 9)
        if check.get("status") == "pass":
            pdf.set_text_color(22, 101, 52)
        else:
            pdf.set_text_color(180, 83, 9)

        pdf.cell(20, 5, status_symbol, 0, 0)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 5, _sanitize(check.get("name", "Check")), ln=True)

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(71, 85, 105)
        pdf.multi_cell(0, 4, _sanitize(f"   {check.get('message', '')}"))
        pdf.ln(1)

    # Section 3: AI Recommendations & Bullet Rewrites
    if ai_feedback:
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 7, "3. Executive Feedback & Suggested Rewrites", ln=True)
        pdf.ln(1)

        exec_summary = ai_feedback.get("executive_summary")
        if exec_summary:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(51, 65, 85)
            pdf.multi_cell(0, 5, _sanitize(exec_summary))
            pdf.ln(2)

        rewrites = ai_feedback.get("bullet_rewrites", [])
        if rewrites:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(0, 5, "Suggested Bullet Point Improvements:", ln=True)
            for item in rewrites[:3]:
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(185, 28, 28)
                pdf.multi_cell(0, 4, _sanitize(f"- Original: {item.get('original', '')}"))
                pdf.set_text_color(22, 101, 52)
                pdf.multi_cell(0, 4, _sanitize(f"+ Rewrite:  {item.get('improved', '')}"))
                pdf.set_text_color(100, 116, 139)
                pdf.multi_cell(0, 4, _sanitize(f"  Reason:   {item.get('reason', '')}"))
                pdf.ln(1)

    return bytes(pdf.output())
